
project_id = "jtnedstugyvkfthtsumh"

[functions.n8n-webhook]
verify_jwt = false

[functions.validate-token]
verify_jwt = false

[functions.stratix-router]
verify_jwt = true

[functions.stratix-stream]
verify_jwt = false
