
import React from 'react';
import { Button } from '@/components/ui/button';
import { Printer, X } from 'lucide-react';
import MarkdownRenderer from './MarkdownRenderer';

interface CanvasPrintViewProps {
  isOpen: boolean;
  onClose: () => void;
  content: string;
  title: string;
}

const CanvasPrintView: React.FC<CanvasPrintViewProps> = ({
  isOpen,
  onClose,
  content,
  title
}) => {
  const handlePrint = () => {
    window.print();
  };

  const handleBackdropClick = (event: React.MouseEvent) => {
    if (event.target === event.currentTarget) {
      onClose();
    }
  };

  if (!isOpen) return null;

  return (
    <div 
      className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm"
      onClick={handleBackdropClick}
    >
      {/* Print controls - hidden when printing */}
      <div className="print:hidden fixed top-4 right-4 z-50 flex gap-2">
        <Button onClick={handlePrint} className="flex items-center gap-2">
          <Printer className="h-4 w-4" />
          Print / Save as PDF
        </Button>
        <Button variant="outline" onClick={onClose} className="flex items-center gap-2">
          <X className="h-4 w-4" />
          Close
        </Button>
      </div>

      {/* Professional Report Container with Pagination */}
      <div 
        className="canvas-print-container"
        data-report-title={title}
        data-generated-date={new Date().toLocaleDateString()}
        data-confidentiality="CONFIDENTIAL"
      >
        {/* Cover Page */}
        <div className="canvas-cover-page page-break-after">
          <div className="cover-header">
            <div className="brand-logo">
              <div className="logo-icon"></div>
              <div className="brand-text">
                <h1>AI Report</h1>
                <p>Generated by AI Assistant</p>
              </div>
            </div>
            <div className="document-type">Canvas Report</div>
          </div>
          
          <div className="cover-main">
            <h1 className="cover-title">{title}</h1>
            <div className="cover-meta">
              <div className="meta-item">
                <span className="meta-label">Generated:</span>
                <span className="meta-value">{new Date().toLocaleDateString()}</span>
              </div>
              <div className="meta-item">
                <span className="meta-label">Type:</span>
                <span className="meta-value">AI Assistant Report</span>
              </div>
            </div>
          </div>
          
          <div className="cover-footer">
            <p className="confidentiality-notice">
              This document contains confidential information generated by AI Assistant
            </p>
          </div>
        </div>

        {/* Main Content */}
        <div className="canvas-content-pages">
          <div className="canvas-markdown-content">
            <MarkdownRenderer content={content} />
          </div>
        </div>
      </div>

      {/* Canvas Print Styles */}
      <style>{`
        @media print {
          @page {
            size: A4;
            margin: 2cm 2.5cm 3cm 2.5cm;
            
            @top-left {
              content: "AI Report";
              font-family: 'Inter', sans-serif;
              font-size: 10pt;
              color: #6b7280;
            }
            
            @top-right {
              content: attr(data-report-title);
              font-family: 'Inter', sans-serif;
              font-size: 10pt;
              color: #6b7280;
              text-align: right;
            }
            
            @bottom-center {
              content: "Page " counter(page);
              font-family: 'Inter', sans-serif;
              font-size: 10pt;
              color: #6b7280;
            }
            
            @bottom-left {
              content: "Generated " attr(data-generated-date);
              font-family: 'Inter', sans-serif;
              font-size: 9pt;
              color: #9ca3af;
            }
            
            @bottom-right {
              content: attr(data-confidentiality);
              font-family: 'Inter', sans-serif;
              font-size: 9pt;
              color: #dc2626;
              font-weight: 600;
            }
          }
          
          /* Cover page without headers/footers */
          @page :first {
            @top-left { content: none; }
            @top-right { content: none; }
            @bottom-center { content: none; }
            @bottom-left { content: none; }
            @bottom-right { content: none; }
          }
          
          .print\\:hidden {
            display: none !important;
          }
          
          body {
            font-family: 'Inter', sans-serif;
            font-size: 11pt;
            line-height: 1.6;
            color: #1f2937;
            background: white;
            margin: 0;
            padding: 0;
          }
          
          .canvas-print-container {
            background: white;
            color: #1f2937;
          }
          
          /* Cover page styles */
          .canvas-cover-page {
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            padding: 40pt;
            background: linear-gradient(135deg, white 0%, #f8fafc 100%);
          }
          
          .cover-header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            margin-bottom: 60pt;
          }
          
          .brand-logo {
            display: flex;
            align-items: center;
            gap: 12pt;
          }
          
          .logo-icon {
            width: 48pt;
            height: 48pt;
            background: linear-gradient(135deg, #2563eb, #3b82f6);
            border-radius: 8pt;
          }
          
          .brand-text h1 {
            font-size: 24pt;
            font-weight: 700;
            color: #1f2937;
            margin: 0;
          }
          
          .brand-text p {
            font-size: 14pt;
            color: #6b7280;
            margin: 0;
          }
          
          .document-type {
            font-size: 12pt;
            color: #6b7280;
            font-weight: 500;
            text-transform: uppercase;
            letter-spacing: 1px;
            padding: 8pt 16pt;
            background: #f1f5f9;
            border-radius: 6pt;
            border-left: 4pt solid #2563eb;
          }
          
          .cover-main {
            text-align: center;
            flex: 1;
            display: flex;
            flex-direction: column;
            justify-content: center;
          }
          
          .cover-title {
            font-size: 36pt;
            font-weight: 700;
            color: #1f2937;
            margin-bottom: 32pt;
            line-height: 1.2;
          }
          
          .cover-meta {
            display: flex;
            justify-content: center;
            gap: 40pt;
          }
          
          .meta-item {
            text-align: left;
          }
          
          .meta-label {
            display: block;
            font-size: 12pt;
            color: #6b7280;
            font-weight: 500;
            margin-bottom: 4pt;
          }
          
          .meta-value {
            display: block;
            font-size: 14pt;
            color: #1f2937;
            font-weight: 600;
          }
          
          .cover-footer {
            text-align: center;
          }
          
          .confidentiality-notice {
            font-size: 10pt;
            color: #9ca3af;
            font-style: italic;
          }
          
          /* Content pages */
          .canvas-content-pages {
            break-before: page;
            padding: 0;
          }
          
          .canvas-markdown-content {
            max-width: none;
            padding: 0;
          }
          
          /* Page break controls */
          .page-break-after {
            break-after: page;
          }
          
          .page-break-before {
            break-before: page;
          }
          
          .page-break-inside-avoid {
            break-inside: avoid;
          }
          
          /* Typography for markdown content */
          .canvas-markdown-content h1 {
            font-size: 24pt;
            font-weight: 700;
            color: #1f2937;
            margin: 32pt 0 16pt 0;
            break-after: avoid;
            orphans: 4;
            widows: 4;
          }
          
          .canvas-markdown-content h2 {
            font-size: 20pt;
            font-weight: 600;
            color: #374151;
            margin: 24pt 0 12pt 0;
            border-bottom: 2pt solid #e5e7eb;
            padding-bottom: 8pt;
            break-after: avoid;
            orphans: 4;
            widows: 4;
          }
          
          .canvas-markdown-content h3 {
            font-size: 16pt;
            font-weight: 600;
            color: #4b5563;
            margin: 20pt 0 10pt 0;
            break-after: avoid;
            orphans: 3;
            widows: 3;
          }
          
          .canvas-markdown-content p {
            margin-bottom: 12pt;
            orphans: 2;
            widows: 2;
          }
          
          .canvas-markdown-content ul, 
          .canvas-markdown-content ol {
            margin-bottom: 16pt;
            break-inside: auto;
          }
          
          .canvas-markdown-content li {
            margin-bottom: 6pt;
            break-inside: avoid;
            orphans: 2;
            widows: 2;
          }
          
          .canvas-markdown-content pre {
            background: #f8fafc;
            border: 1pt solid #e2e8f0;
            border-radius: 6pt;
            padding: 16pt;
            font-size: 10pt;
            overflow: visible;
            white-space: pre-wrap;
            break-inside: avoid;
            margin: 16pt 0;
          }
          
          .canvas-markdown-content code {
            background: #f1f5f9;
            padding: 2pt 4pt;
            border-radius: 3pt;
            font-size: 10pt;
          }
          
          .canvas-markdown-content blockquote {
            border-left: 4pt solid #e5e7eb;
            padding-left: 16pt;
            margin: 16pt 0;
            font-style: italic;
            color: #6b7280;
            break-inside: avoid;
          }
          
          .canvas-markdown-content table {
            width: 100%;
            border-collapse: collapse;
            margin: 16pt 0;
            break-inside: avoid;
          }
          
          .canvas-markdown-content th,
          .canvas-markdown-content td {
            border: 1pt solid #e5e7eb;
            padding: 8pt 12pt;
            text-align: left;
          }
          
          .canvas-markdown-content th {
            background: #f8fafc;
            font-weight: 600;
          }
        }
      `}</style>
    </div>
  );
};

export default CanvasPrintView;
