// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtnedstugyvkfthtsumh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0bmVkc3R1Z3l2a2Z0aHRzdW1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDYzMzUsImV4cCI6MjA2NDA4MjMzNX0.RGo9HmL3z73S545MwJ4RewZ_jxq1yDDP748maW7PJSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);